import { Element } from './Element.js'
import { ConditionalExpression } from './ConditionalExpression.js'
import { HtmlCode } from './HtmlCode.js'

export function IF(condition){
	return new ConditionalExpression(condition)
}

export function HTML(htmlCode){
	return new HtmlCode(htmlCode)
}

function createElementCreator(tagName){
	return new Proxy(function(){}, {
		get(target, prop, receiver){
			// E.g. Div.class
			return new Element(tagName)[prop]
		},
		apply: function(target, thisArg, argumentsList){
			// E.g. Div("content")
			return new Element(tagName, argumentsList)
		}
	})
}

export const A = createElementCreator('a')
export const Abbr = createElementCreator('abbr')
export const Address = createElementCreator('address')
export const Area = createElementCreator('area')
export const Article = createElementCreator('article')
export const Aside = createElementCreator('aside')
export const Audio = createElementCreator('audio')
export const B = createElementCreator('b')
export const Base = createElementCreator('base')
export const Bb = createElementCreator('bb')
export const Bdo = createElementCreator('bdo')
export const Blockquote = createElementCreator('blockquote')
export const Body = createElementCreator('body')
export const Br = createElementCreator('br')
export const Button = createElementCreator('button')
export const Canvas = createElementCreator('canvas')
export const Caption = createElementCreator('caption')
export const Cite = createElementCreator('cite')
export const Code = createElementCreator('code')
export const Col = createElementCreator('col')
export const Colgroup = createElementCreator('colgroup')
export const Command = createElementCreator('command')
export const Datagrid = createElementCreator('datagrid')
export const Datalist = createElementCreator('datalist')
export const Dd = createElementCreator('dd')
export const Del = createElementCreator('del')
export const Details = createElementCreator('details')
export const Dfn = createElementCreator('dfn')
export const Dialog = createElementCreator('dialog')
export const Div = createElementCreator('div')
export const Dl = createElementCreator('dl')
export const Dt = createElementCreator('dt')
export const Em = createElementCreator('em')
export const Embed = createElementCreator('embed')
export const Eventsource = createElementCreator('eventsource')
export const Fieldset = createElementCreator('fieldset')
export const Figcaption = createElementCreator('figcaption')
export const Figure = createElementCreator('figure')
export const Footer = createElementCreator('footer')
export const Form = createElementCreator('form')
export const H1 = createElementCreator('h1')
export const H2 = createElementCreator('h2')
export const H3 = createElementCreator('h3')
export const H4 = createElementCreator('h4')
export const H5 = createElementCreator('h5')
export const H6 = createElementCreator('h6')
export const Head = createElementCreator('head')
export const Header = createElementCreator('header')
export const Hgroup = createElementCreator('hgroup')
export const Hr = createElementCreator('hr')
export const Html = createElementCreator('html')
export const I = createElementCreator('i')
export const Iframe = createElementCreator('iframe')
export const Img = createElementCreator('img')
export const Input = createElementCreator('input')
export const Ins = createElementCreator('ins')
export const Kbd = createElementCreator('kbd')
export const Keygen = createElementCreator('keygen')
export const Label = createElementCreator('label')
export const Legend = createElementCreator('legend')
export const Li = createElementCreator('li')
export const Link = createElementCreator('link')
export const Main = createElementCreator('main')
export const Map = createElementCreator('map')
export const Mark = createElementCreator('mark')
export const Menu = createElementCreator('menu')
export const Meta = createElementCreator('meta')
export const Meter = createElementCreator('meter')
export const Nav = createElementCreator('nav')
export const Noscript = createElementCreator('noscript')
export const Object = createElementCreator('object')
export const Ol = createElementCreator('ol')
export const Optgroup = createElementCreator('optgroup')
export const Option = createElementCreator('option')
export const Output = createElementCreator('output')
export const P = createElementCreator('p')
export const Param = createElementCreator('param')
export const Pre = createElementCreator('pre')
export const Progress = createElementCreator('progress')
export const Q = createElementCreator('q')
export const Rp = createElementCreator('rp')
export const Rt = createElementCreator('rt')
export const Ruby = createElementCreator('ruby')
export const S = createElementCreator('s')
export const Samp = createElementCreator('samp')
export const Script = createElementCreator('script')
export const Section = createElementCreator('section')
export const Select = createElementCreator('select')
export const Small = createElementCreator('small')
export const Source = createElementCreator('source')
export const Span = createElementCreator('span')
export const Strong = createElementCreator('strong')
export const Style = createElementCreator('style')
export const Sub = createElementCreator('sub')
export const Sup = createElementCreator('sup')
export const Table = createElementCreator('table')
export const Tbody = createElementCreator('tbody')
export const Td = createElementCreator('td')
export const Textarea = createElementCreator('textarea')
export const Tfoot = createElementCreator('tfoot')
export const Th = createElementCreator('th')
export const Thead = createElementCreator('thead')
export const Time = createElementCreator('time')
export const Title = createElementCreator('title')
export const Tr = createElementCreator('tr')
export const Track = createElementCreator('track')
export const U = createElementCreator('u')
export const Ul = createElementCreator('ul')
export const Var = createElementCreator('var')
export const Video = createElementCreator('video')
export const Wbr = createElementCreator('wbr')